### PR TITLE
Fix initialization of Media objects

### LINKED ISSUE #4: Possible to register multiple apps with same name
I've confirmed that I can register two apps with the same name on the same instance via Oauth:

screenshot

This probably should be prevented in order to keep people from spoofing other apps, though I'm no security expert so maybe this isn't an issue at all.

### PR DESCRIPTION
**Pull request by muffinista**
Fixes  #4

### CODE REVIEW

File: lib/mastodon/rest/request.rb [hunk 1]
```diff
@@ -19,6 +19,8 @@ def initialize(client, request_method, path, options = {})
       def perform
         options_key = @request_method == :get ? :params : :form
         response    = http_client.headers(@headers).public_send(@request_method, @uri.to_s, options_key => @options)
+        STDERR.puts response.body if ENV['DEBUG'] == 'true'
```
Comment (Gargron) [inline lib/mastodon/rest/request.rb]: Hmm there is a wonderful gem called httplog which can be set to log outgoing requests and responses, you could use that for debugging.
